"""Add GIS models

Revision ID: 818c42499a31
Revises: 90676b09977a
Create Date: 2026-09-04 01:06:26.953030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818c42499a31'
down_revision: Union[str, Sequence[str], None] = '90676b09977a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bottlenecks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bottleneck_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('geometry_geojson', sa.String(), nullable=True),
    sa.Column('blocked_length_km', sa.Float(), nullable=True),
    sa.Column('affected_parcels', sa.Integer(), nullable=True),
    sa.Column('high_risk_parcels', sa.Integer(), nullable=True),
    sa.Column('spatial_criticality', sa.String(), nullable=True),
    sa.Column('continuity_blocked', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bottlenecks_bottleneck_id'), 'bottlenecks', ['bottleneck_id'], unique=True)
    op.create_index(op.f('ix_bottlenecks_id'), 'bottlenecks', ['id'], unique=False)
    op.create_index(op.f('ix_bottlenecks_project_id'), 'bottlenecks', ['project_id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('geometry_geojson', sa.String(), nullable=True),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('acquisition_status', sa.String(), nullable=True),
    sa.Column('compensation_status', sa.String(), nullable=True),
    sa.Column('legal_status', sa.String(), nullable=True),
    sa.Column('acquisition_duration_months', sa.Integer(), nullable=True),
    sa.Column('affected_parties', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('spatial_criticality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=False)
    op.create_index(op.f('ix_parcels_parcel_id'), 'parcels', ['parcel_id'], unique=True)
    op.create_index(op.f('ix_parcels_project_id'), 'parcels', ['project_id'], unique=False)
    op.create_table('project_corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('geometry_geojson', sa.String(), nullable=True),
    sa.Column('total_length_km', sa.Float(), nullable=True),
    sa.Column('acquired_length_km', sa.Float(), nullable=True),
    sa.Column('pending_length_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_corridors_id'), 'project_corridors', ['id'], unique=False)
    op.create_index(op.f('ix_project_corridors_project_id'), 'project_corridors', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_corridors_project_id'), table_name='project_corridors')
    op.drop_index(op.f('ix_project_corridors_id'), table_name='project_corridors')
    op.drop_table('project_corridors')
    op.drop_index(op.f('ix_parcels_project_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_parcel_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_bottlenecks_project_id'), table_name='bottlenecks')
    op.drop_index(op.f('ix_bottlenecks_id'), table_name='bottlenecks')
    op.drop_index(op.f('ix_bottlenecks_bottleneck_id'), table_name='bottlenecks')
    op.drop_table('bottlenecks')
    # ### end Alembic commands ###
