// Synthetic data for the GIS Intelligence prototype

export const gisProjects = [
  {
    projectId: "P-1042",
    projectName: "NH-48 Jaipur–Kishangarh Expansion",
    state: "Rajasthan",
    district: "Jaipur",
    latitude: 26.9124,
    longitude: 75.7873,
    landArea: 486,
    affectedFamilies: 312,
    currentStage: "Compensation",
    riskScore: 78,
    riskLevel: "HIGH",
    riskTrend: "Increasing",
    primaryDriver: "Pending Compensation",
    actionStatus: "Action Required"
  },
  {
    projectId: "P-1038",
    projectName: "Jaipur Ring Road Expansion",
    state: "Rajasthan",
    district: "Jaipur",
    latitude: 26.7824,
    longitude: 75.8273,
    landArea: 320,
    affectedFamilies: 250,
    currentStage: "R&R",
    riskScore: 84,
    riskLevel: "CRITICAL",
    riskTrend: "Increasing",
    primaryDriver: "Low R&R Progress",
    actionStatus: "Assigned"
  },
  {
    projectId: "P-1019",
    projectName: "Ajmer Bypass Acquisition",
    state: "Rajasthan",
    district: "Ajmer",
    latitude: 26.4499,
    longitude: 74.6399,
    landArea: 215,
    affectedFamilies: 140,
    currentStage: "Declaration",
    riskScore: 67,
    riskLevel: "HIGH",
    riskTrend: "Stable",
    primaryDriver: "Approval Delay",
    actionStatus: "In Progress"
  },
  {
    projectId: "P-1071",
    projectName: "Jodhpur Peripheral Road",
    state: "Rajasthan",
    district: "Jodhpur",
    latitude: 26.2389,
    longitude: 73.0243,
    landArea: 247,
    affectedFamilies: 180,
    currentStage: "SIA / Assessment",
    riskScore: 43,
    riskLevel: "MEDIUM",
    riskTrend: "Decreasing",
    primaryDriver: "Stakeholder Responsiveness",
    actionStatus: "Completed"
  },
  {
    projectId: "P-1092",
    projectName: "Kota Industrial Park Setup",
    state: "Rajasthan",
    district: "Kota",
    latitude: 25.1825,
    longitude: 75.8391,
    landArea: 188,
    affectedFamilies: 95,
    currentStage: "Compensation",
    riskScore: 61,
    riskLevel: "HIGH",
    riskTrend: "Increasing",
    primaryDriver: "Pending Compensation",
    actionStatus: "Assigned"
  },
  {
    projectId: "P-1104",
    projectName: "Alwar Smart City Expansion",
    state: "Rajasthan",
    district: "Alwar",
    latitude: 27.5530,
    longitude: 76.6346,
    landArea: 176,
    affectedFamilies: 110,
    currentStage: "Possession",
    riskScore: 52,
    riskLevel: "MEDIUM",
    riskTrend: "Stable",
    primaryDriver: "Legal Dispute",
    actionStatus: "Monitoring"
  },
  {
    projectId: "P-1122",
    projectName: "Udaipur Heritage Zone Bypass",
    state: "Rajasthan",
    district: "Udaipur",
    latitude: 24.5854,
    longitude: 73.7125,
    landArea: 120,
    affectedFamilies: 80,
    currentStage: "Preliminary Notification",
    riskScore: 28,
    riskLevel: "LOW",
    riskTrend: "Decreasing",
    primaryDriver: "Approval Delay",
    actionStatus: "Completed"
  },
  {
    projectId: "P-1150",
    projectName: "Jaipur IT SEZ",
    state: "Rajasthan",
    district: "Jaipur",
    latitude: 26.8200,
    longitude: 75.7500,
    landArea: 150,
    affectedFamilies: 45,
    currentStage: "Compensation",
    riskScore: 88,
    riskLevel: "CRITICAL",
    riskTrend: "Increasing",
    primaryDriver: "Pending Compensation",
    actionStatus: "Action Required"
  },
  {
    projectId: "P-1165",
    projectName: "Bikaner Solar Park Access",
    state: "Rajasthan",
    district: "Bikaner",
    latitude: 28.0229,
    longitude: 73.3119,
    landArea: 600,
    affectedFamilies: 50,
    currentStage: "Declaration",
    riskScore: 35,
    riskLevel: "LOW",
    riskTrend: "Stable",
    primaryDriver: "Stakeholder Responsiveness",
    actionStatus: "Monitoring"
  },
  {
    projectId: "P-1178",
    projectName: "Jaipur Metro Phase 3 Depot",
    state: "Rajasthan",
    district: "Jaipur",
    latitude: 26.8500,
    longitude: 75.8000,
    landArea: 40,
    affectedFamilies: 120,
    currentStage: "R&R",
    riskScore: 72,
    riskLevel: "HIGH",
    riskTrend: "Increasing",
    primaryDriver: "Low R&R Progress",
    actionStatus: "In Progress"
  },
  {
    projectId: "P-1190",
    projectName: "Ajmer Lake Front Development",
    state: "Rajasthan",
    district: "Ajmer",
    latitude: 26.4600,
    longitude: 74.6500,
    landArea: 35,
    affectedFamilies: 80,
    currentStage: "Compensation",
    riskScore: 65,
    riskLevel: "HIGH",
    riskTrend: "Stable",
    primaryDriver: "Legal Dispute",
    actionStatus: "Action Required"
  },
  {
    projectId: "P-1205",
    projectName: "Jodhpur Logistics Hub",
    state: "Rajasthan",
    district: "Jodhpur",
    latitude: 26.2000,
    longitude: 73.0500,
    landArea: 310,
    affectedFamilies: 60,
    currentStage: "Possession",
    riskScore: 48,
    riskLevel: "MEDIUM",
    riskTrend: "Decreasing",
    primaryDriver: "Approval Delay",
    actionStatus: "Completed"
  },
  {
    projectId: "P-1218",
    projectName: "Kota Education City Roads",
    state: "Rajasthan",
    district: "Kota",
    latitude: 25.2000,
    longitude: 75.8500,
    landArea: 85,
    affectedFamilies: 210,
    currentStage: "SIA / Assessment",
    riskScore: 55,
    riskLevel: "MEDIUM",
    riskTrend: "Increasing",
    primaryDriver: "Stakeholder Responsiveness",
    actionStatus: "Assigned"
  },
  {
    projectId: "P-1234",
    projectName: "Alwar Industrial Estate 2",
    state: "Rajasthan",
    district: "Alwar",
    latitude: 27.5700,
    longitude: 76.6500,
    landArea: 140,
    affectedFamilies: 30,
    currentStage: "Compensation",
    riskScore: 79,
    riskLevel: "HIGH",
    riskTrend: "Increasing",
    primaryDriver: "Pending Compensation",
    actionStatus: "Action Required"
  },
  {
    projectId: "P-1249",
    projectName: "Jaipur East Bypass",
    state: "Rajasthan",
    district: "Jaipur",
    latitude: 26.8800,
    longitude: 75.8800,
    landArea: 220,
    affectedFamilies: 160,
    currentStage: "Declaration",
    riskScore: 68,
    riskLevel: "HIGH",
    riskTrend: "Stable",
    primaryDriver: "Approval Delay",
    actionStatus: "Assigned"
  }
];

export const gisClusters = [
  {
    id: "C-01",
    name: "Jaipur Urban Corridor",
    projects: 5,
    avgRisk: 78,
    primaryDriver: "Pending Compensation",
    landArea: 1216,
    trend: "Increasing"
  },
  {
    id: "C-02",
    name: "Ajmer Infrastructure Belt",
    projects: 2,
    avgRisk: 66,
    primaryDriver: "Approval Delay",
    landArea: 250,
    trend: "Stable"
  },
  {
    id: "C-03",
    name: "Jodhpur Peripheral Corridor",
    projects: 2,
    avgRisk: 46,
    primaryDriver: "Stakeholder Responsiveness",
    landArea: 557,
    trend: "Decreasing"
  },
  {
    id: "C-04",
    name: "Kota Manufacturing Zone",
    projects: 2,
    avgRisk: 58,
    primaryDriver: "Pending Compensation",
    landArea: 273,
    trend: "Increasing"
  },
  {
    id: "C-05",
    name: "Alwar Tech Hub",
    projects: 2,
    avgRisk: 66,
    primaryDriver: "Legal Dispute",
    landArea: 316,
    trend: "Stable"
  }
];
